apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/Just4Being/apps.git
    targetRevision: HEAD
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
